### PR TITLE
UI Tweaks

### PR DESCRIPTION
**Pull request by InsaneWookie**
Moved some buttons inline with the select boxesS
Moved the information text under the labels
Moved armor buttons side by side
Some minor code tidy ups

image
image

### CODE REVIEW

**Comment by Perlkonig** [comment]
Thank you for the PR! I deliberately removed `is-grouped` because it overflowed horizontally on mobile browsers. I'll pull this in and do some testing.

**Comment by Perlkonig** [comment]
Made the armour buttons smaller so they can stay grouped and not horizontally overflow on mobile. New release imminent. Thanks again.

**Comment by InsaneWookie** [comment]
All good. 
I probably should have asked about PRs before just randomly firing one in :D

**Comment by Perlkonig** [comment]
Not at all. I love random PRs 😀

**Pull request merged**
